# Archivo de prueba
# Ejemplo de formato de class Student
print("Ejemplo type1 integer")
print(type(50))
print()
print("Ejemplo type2 string")
print(type("hola"))
print()
print("Ejemplo type3 list corchetes")
print(type([]))
print()
print("Ejemplo type4 list()")
print(type(list()))
print()
print("Ejemplo type5 llaves")
print(type({}))
print()
print("Ejemplo type6 dict()")
print(type(dict()))
print()
